# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: protos/leader.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13protos/leader.proto\x12\x06leader\"#\n\x0bLearnerInfo\x12\x14\n\x0cnetwork_addr\x18\x01 \x01(\t\"*\n\x12LearnerDataRequest\x12\x14\n\x0cnetwork_addr\x18\x01 \x01(\t\"]\n\x0f\x41\x63kWithMetadata\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x12\n\nlearner_id\x18\x03 \x01(\x05\x12\x14\n\x0cmax_learners\x18\x04 \x01(\x05\"\'\n\x03\x41\x63k\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\"\x07\n\x05\x45mpty\"\x1b\n\nModelChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"\x1a\n\tDataChunk\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\"\x1d\n\x0cGradientData\x12\r\n\x05\x63hunk\x18\x01 \x01(\x0c\x32\xff\x01\n\rLeaderService\x12\x41\n\x0fRegisterLearner\x12\x13.leader.LearnerInfo\x1a\x17.leader.AckWithMetadata\"\x00\x12\x31\n\x08GetModel\x12\r.leader.Empty\x1a\x12.leader.ModelChunk\"\x00\x30\x01\x12<\n\x07GetData\x12\x1a.leader.LearnerDataRequest\x1a\x11.leader.DataChunk\"\x00\x30\x01\x12:\n\x13\x41\x63\x63umulateGradients\x12\x14.leader.GradientData\x1a\x0b.leader.Ack\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.leader_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_LEARNERINFO']._serialized_start=31
  _globals['_LEARNERINFO']._serialized_end=66
  _globals['_LEARNERDATAREQUEST']._serialized_start=68
  _globals['_LEARNERDATAREQUEST']._serialized_end=110
  _globals['_ACKWITHMETADATA']._serialized_start=112
  _globals['_ACKWITHMETADATA']._serialized_end=205
  _globals['_ACK']._serialized_start=207
  _globals['_ACK']._serialized_end=246
  _globals['_EMPTY']._serialized_start=248
  _globals['_EMPTY']._serialized_end=255
  _globals['_MODELCHUNK']._serialized_start=257
  _globals['_MODELCHUNK']._serialized_end=284
  _globals['_DATACHUNK']._serialized_start=286
  _globals['_DATACHUNK']._serialized_end=312
  _globals['_GRADIENTDATA']._serialized_start=314
  _globals['_GRADIENTDATA']._serialized_end=343
  _globals['_LEADERSERVICE']._serialized_start=346
  _globals['_LEADERSERVICE']._serialized_end=601
# @@protoc_insertion_point(module_scope)
