# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from protos import learner_pb2 as protos_dot_learner__pb2


class LearnerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.StartTraining = channel.unary_unary(
                '/learner.LearnerService/StartTraining',
                request_serializer=protos_dot_learner__pb2.Empty.SerializeToString,
                response_deserializer=protos_dot_learner__pb2.Ack.FromString,
                )
        self.SyncModelState = channel.unary_unary(
                '/learner.LearnerService/SyncModelState',
                request_serializer=protos_dot_learner__pb2.ModelState.SerializeToString,
                response_deserializer=protos_dot_learner__pb2.Ack.FromString,
                )


class LearnerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def StartTraining(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SyncModelState(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LearnerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'StartTraining': grpc.unary_unary_rpc_method_handler(
                    servicer.StartTraining,
                    request_deserializer=protos_dot_learner__pb2.Empty.FromString,
                    response_serializer=protos_dot_learner__pb2.Ack.SerializeToString,
            ),
            'SyncModelState': grpc.unary_unary_rpc_method_handler(
                    servicer.SyncModelState,
                    request_deserializer=protos_dot_learner__pb2.ModelState.FromString,
                    response_serializer=protos_dot_learner__pb2.Ack.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'learner.LearnerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class LearnerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def StartTraining(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.LearnerService/StartTraining',
            protos_dot_learner__pb2.Empty.SerializeToString,
            protos_dot_learner__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def SyncModelState(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/learner.LearnerService/SyncModelState',
            protos_dot_learner__pb2.ModelState.SerializeToString,
            protos_dot_learner__pb2.Ack.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
